---

- hosts: web_servers
  become: true
  pre_tasks:

  - name: install apache2 and php packages (Ubuntu)
    package:  #finds and runs the appropriate package manager in the specified server
      name: 
        - apache2
        - php
        - php-mysql 
        - php-curl 
        - php-gd 
        - php-json 
        - php-zip 
        - php-mbstring 
        - php-gettext
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"    

  - name: install mysql-server (ubuntu)
    apt:
      name:
        - mysql-server
    when: ansible_distribution == "Ubuntu"      
        


  
    

